# Generated by Django 5.0 on 2023-12-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['id']},
        ),
    ]
