# Generated by Django 5.0 on 2023-12-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_task_board_alter_task_options_task_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='todo',
            field=models.BooleanField(default=True),
        ),
    ]
