# Generated by Django 5.0 on 2023-12-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_task_started_task_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='started',
        ),
        migrations.RemoveField(
            model_name='task',
            name='todo',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('started', 'Started'), ('complete', 'Complete')], default='todo', max_length=20),
        ),
    ]
