# Generated by Django 5.0 on 2023-12-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_options_remove_task_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('started', 'Started'), ('complete', 'Complete'), ('archived', 'Archived')], default='todo', max_length=20),
        ),
    ]
